### ISSUE TITLE
eRg_EntryTailDiscard missing from CM88 parquet length PDO

### ISSUE THREAD

**Issue by zennet-novelis** [novelis-prod/Digital-CoE-Operations-Data---Public#62]
**eRg_EntryTailDiscard** signal was present in parquet output of PDO from May data. The signal is presently missing in June data for both CM72 and CM88.

**Comment by zennet-novelis** [comment]
Reported by @KrishnaMaddipati

**Comment by guptaad** [comment]
As discussed; finish the hotmill pipeline first, and then triage this.

**Comment by zennet-novelis** [comment]
We discussed this issue in a call with Manko this morning. It looks like the problem is more complex that I had originally thought (wrong version of PDO) and we need to do more testing on coil files from May and June using Filtered pdo and Parquet length pdo to find out what is causing this and what we can do to fix it.

Raimund has spent about two hours looking into the cause.

**Comment by zennet-novelis** [comment]
Raimund and I spent 90 minutes looking at this and testing combinations of PDOs and Dat files for CM88.

It looks like there are three distinct bugs causing this issue:
1. Calculation discard was never implemented in raw to parquet length PDO
2. Zip Shear In Solenoid signal is not recorded properly in many files tested
3. Discard signal calculation is high than the coil length in CM72 PDO

filename | May9_0318164_2_X320_70.0_036.0_019.5 | May22_0316492_2_5182_69.0_089.0_059.1 | May23_0318894_1_X320_59.3_080.0_036.0 | May26_0318963_3_X320_59.3_019.6_010.6 | May30_0318688_1_X615_72.3_197.0_080.0 | June03_0319413_1_X320_61.0_085.0_036.0 | June05_0319413_3_X320_61.0_019.9_011.5 | June25_0321361_1_X330_67.0_085.0_036.0
-- | -- | -- | -- | -- | -- | -- | -- | --
OSW_CM88_20200421 | 206 | 215 | 0 | 0 | 0 | 0 | 209 | 0
OSW_CM88_Lengthbased20200504 | NaN |   |   |   |   |   |   | 0
OSW_CM88_raw2filtered | 0 |   |   |   |   |   |   | 0
osw_cm88_raw2parquet_length | hung |   |   |   |   |   |   | hung

**Comment by zennet-novelis** [comment]
I sent Manko our results and he can work on fixing number 1. from above.

**Comment by guptaad** [comment]
Update: Raimund is following up with Roberto and Felipe - there seems to be a rule issue, which needs to be updated.

**Comment by RaimundNovelis** [comment]
After our 1 1/2 hour meeting with Felipe to solve the problem for CM88 we were not able to finish it and we came to the decission, that we really need a process which describes the handling of the global catalogs and resulting PDOs. Most of the things really went wrong in the past. Macros were only locally changed in the pdo but not on a global level. Signal changes and additions were only made in the pdo, but not in the site level catalog or even the global catalog. Signals and Units were not mapped correct --> due to this the macros were adjusted, which is the wrong way in doing it and this caused additional problems in different places. Still our knowledge on the whole ibaAnalyzer calculations (this also includes the macro functions) is far away from experts. Missing documentation of macros also doesn't make things easier.

We will have a meeting with Manko and Felipe today, to work on this kind of process and see how we can fix these issues. I think we may have same problems for other machine centers in other plants, because I assume parts of the work was made in the same way.

Main Points for the Meeting:

- Using centralizided storage for versioning of Global Catalogs and Macros
- Changemangement (Global Catalog, Site Level Mapping, Excel Macros,  PDO,  PDO Macros etc.)
- Working colaborative with diffenrent teams (ME, DE, IBA)

**Comment by guptaad** [comment]
@khancynthia28 please test the #1 - Calculation discard was never implemented in raw to parquet length PDO

**Comment by zennet-novelis** [comment]
Created #80 and #81 to resolve 2. and 3. from above.

> 1. Calculation discard was never implemented in raw to parquet length PDO
> 2. Zip Shear In Solenoid signal is not recorded properly in many files tested
> 3. Discard signal calculation is greater than the coil length in CM72 PDO

**Comment by zennet-novelis** [comment]
The expression for eRg_EntryTailDiscard is in the parquet length pdo. I ran it for July 1 to July 8 data. Next step is to see whether this unblocks loading into the delta lake.

And the related issue #81 turns out to be true, also. It looks like there are dat files that are missing this signal where the shouldn't be. We will track that issue separately and this one can be resolved.

**Comment by khancynthia28** [comment]
@zennet-novelis @KrishnaMaddipati Can we close this issue?

**Comment by khancynthia28** [comment]
@zennet-novelis @guptaad 
![image](https://user-images.githubusercontent.com/34836475/87573706-536b6880-c69b-11ea-8288-e22675d47bb8.png)

A large number of records from Jun and May still has the Entry Tail value as null. July doesn't seem to have the issue. Is this a WIP then or should we close?

**Comment by zennet-novelis** [comment]
@khancynthia28 
If you can validate it is fixed for July 1 to today, then we can close.
The issue is about fixing it, not applying the fix to all the historical data.

**Comment by khancynthia28** [comment]
@zennet-novelis In that case, as I have already mentioned, the issue doesn't seem to appear for July

![image](https://user-images.githubusercontent.com/34836475/87730161-04a1f980-c795-11ea-8d72-571d6148ebc1.png)


And since you are the originator of this ticket, I'll leave it to you to close it.
