### ISSUE TITLE
Data missing from Remelt (compared with PI)

### ISSUE THREAD

**Issue by WilberDelbrison** [novelis-prod/Digital-CoE-Operations-Data---Public#70]
I got with Rodrigo a list with all Batch_id produced at Pinda in 2019/2020, so I summarized by caster, year, and month to compare with the number of batches we have in Databricks. We have missing batches in almost all months:
Line D:
![image](https://user-images.githubusercontent.com/58709749/86046837-4d7f5180-ba24-11ea-94f6-aa75e22d9376.png)
Line C:
![image](https://user-images.githubusercontent.com/58709749/86046888-625be500-ba24-11ea-80cf-e32ee110c9f0.png)
Line B:
![image](https://user-images.githubusercontent.com/58709749/86046958-7869a580-ba24-11ea-99ba-3c7785b23668.png)
Line A:
![image](https://user-images.githubusercontent.com/58709749/86046999-8ddecf80-ba24-11ea-8af6-df172664a685.png)
[Batchs PI_vs_Databricks.xlsx](https://github.com/novelis-prod/Digital-CoE-Operations-Data---Public/files/4847597/Batchs.PI_vs_Databricks.xlsx)
[Batchs_produced_Remelt.xlsx](https://github.com/novelis-prod/Digital-CoE-Operations-Data---Public/files/4847609/Batchs_produced_Remelt.xlsx)

**Comment by khancynthia28** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/34836475/86772928-f16b8d00-c022-11ea-9645-65a30961e235.png)

**Comment by khancynthia28** [comment]
LineD now has over 90% of the total expected batches for the months in 2020. The diff of 9 batches per month is due to NDB missing out on the last day's data (schedule of 01/01/2020 - 01/31/2020 doesn't include 01/31).

Currently working on fixing the data gaps for LineB and LineC along with the last day of the month for LineD.

**Comment by khancynthia28** [comment]
![image](https://user-images.githubusercontent.com/34836475/86920132-424cb580-c0f7-11ea-9ac2-b74fedf6f334.png)

**Comment by khancynthia28** [comment]
![image](https://user-images.githubusercontent.com/34836475/87087948-f89cc180-c201-11ea-8295-29d59d5f10ad.png)

**Comment by khancynthia28** [comment]
![image](https://user-images.githubusercontent.com/34836475/87628608-5b5cf400-c6ff-11ea-920a-db04abc9a092.png)

Batch count from LineA_DC_A

**Comment by khancynthia28** [comment]
@WilberDelbrison We have now been able to restore atleast 90% of the batches compared to the data provided by Rodrigo. The only exception is Line A_DC_A, which per Rodrigo's spreadsheet should have 37 batches in May 2020 but per the account from delta table has only 3 batches for that month. Upon taking a closer look at the data provided by Rodrigo this is what I found:

**Comment by khancynthia28** [comment]
![image](https://user-images.githubusercontent.com/34836475/87628880-e5a55800-c6ff-11ea-8048-ba843a98387f.png)

**Comment by khancynthia28** [comment]
These are all the batches along with timestamps recorded from Line A_DC_A by PI DataLink directly. This shows that there are 37 rows in May but only 3 unique batch id values - 45233/36, 45237/40 and I/O Timeout/I/O Timeout. This confirms both Rodrigo's data (37) and the data in the Delta table (3). 

And by the same reasoning I believe we can prove that the difference of batches between Rodrigo's data and the data from Delta table for other lines is also due to looking at row counts versus distinct batch ids. I have the entire list of batch ids from the PI DataLink for all four lines just like the snippet provided above. If needed we can sift through the list and verify this theory. 

However, at this point, since we do have more than 90% of the batches for 2020, I propose to close this issue. 

@WilberDelbrison Can we close this one?

**Comment by khancynthia28** [comment]
@WilberDelbrison Hi Wilber, closing this for now. Please reopen if you still find errors. Thanks.
