### ISSUE TITLE
Oswego PI System_Gen_Alloy_dg and master_batch_id

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#88]
question

Looking through the Osw PI data for melter, holder, and caster I came across values such as No Data, Unknown, Scan Timeout. These values are then translated to the master_batch_id.

![image](https://user-images.githubusercontent.com/58708978/87048852-3f6ec500-c1ca-11ea-8f85-5c6605e4465f.png)
![image](https://user-images.githubusercontent.com/58708978/87049012-6f1dcd00-c1ca-11ea-8263-0b06f5a63d89.png)
![image](https://user-images.githubusercontent.com/58708978/87049035-78a73500-c1ca-11ea-978b-3ff0a07e8c56.png)
![image](https://user-images.githubusercontent.com/58708978/87049068-8361ca00-c1ca-11ea-936e-cd553918c04f.png)
![image](https://user-images.githubusercontent.com/58708978/87049200-ab512d80-c1ca-11ea-9b65-f290990a3143.png)

**Comment by khancynthia28** [comment]
@RyanNovelis As discussed earlier today, the master_batch_id is dependent on the batch_id and has no bearing on Alloy. However, since PI produces time series data, during times when there are no batches in production the signals may be assigned values such as NoData etc. As such, it is best to drop the unexpected values from master_batch_id and Alloy columns and then perform data processing on those columns. 

Does that answer your question?

**Comment by RyanNovelis** [comment]
@khancynthia28 Yes this does. Thank you and I will proceed accordingly.
