### ISSUE TITLE
Alloy tag missing from Pinda Holder

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#92]
Pinda holder does not contain Alloy tag.

![image](https://user-images.githubusercontent.com/58708978/87813171-62831f80-c82f-11ea-9b46-55880d621af1.png)

**Comment by khancynthia28** [comment]
@RyanNovelis Alloy info is recorded only during the Casting process. In addition, the Alloy of a batch doesn't change and remains the same throughout the process. Therefore, we get Alloy info from either of the three processes (usually Caster) and then infer it to the rest of the process by association of Batch ID if needed. Closing this issue since Pinda Caster already has Alloy info.
